---
title: "ARMA Simulation"
author: "Aron Hartvig"
date: "09/03/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
fig_width: 5
fig_height: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create the function

ARMA processes has two parts, the AR(p) and the MA(q) part. We can simply simulate an ARMA process by multiplying the matrix of coefficients and the lags of Ys and errors.

```{r function}
ARMASimulation <- function( N = 1000, ar = c( 0 ), ma = c( 0 ), sd ){
  ar_lag <- length( ar ) # p
  ma_lag <- length( ma ) # q
  max_lag <- max( ar_lag, ma_lag )
  sim_data = rep( NA, ( N + max_lag ) ) 
  # Create empty vector
  sim_data[ 1:max_lag ] <- 0 
  # Set first max(p,q) items 0
  epsilon <- rnorm( N + max_lag + 1, mean = 0, sd = sd ) 
  # Vector of errors
  
  for( i in (max_lag + 1):(N + max_lag)){
    sim_data[ i ] <- ar %*% sim_data[ c( (i - 1):(i - ar_lag) )] +
      epsilon[ i ] + ma %*% epsilon[ c( (i - 1):(i - ma_lag) )]
  }
  plot( sim_data, type = "l" )
  return( sim_data[ -c( 1:max_lag ) ] )
}
```

## Run the function

Try it with specific values, to see if it works.

```{r input, fig.height = 2.5, fig.width = 7}
N <- 1000
ar <- c( 1 )
sd <- 10
ARMA <- ARMASimulation( N, ar, sd = sd ) # Random walk
```

```{r expo, fig.height = 2.5, fig.width = 7}
ar <- c( 1.01 )
ARMA <- ARMASimulation( N, ar, sd = sd ) # Exponential
```

```{r normal, fig.height = 2.5, fig.width = 7}
ar <- c( 0.3, 0.2, 0.02 )
ma <- c( 0.1, 0.03 )
ARMA <- ARMASimulation( N, ar, ma, sd ) # Stationer
```



